tasks:
  - name: cors-host-config
    before: bash hostURL.sh
    command: gp open README.md
  - name: graphQL-Client
    before: |
      nvm install node
      npm install -g npm@latest
      npm install astra-setup
      npm install -g netlify-cli
      npm install
    command: |
      echo "workshop-vuejs gitpod ready - LET'S DO THIS!"
ports:
  - port: 8888
    onOpen: open-preview
  - port: 8080
    visibility: public
    onOpen: open-browser
  - port: 3000
    onOpen: ignore      
github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: false
    addCheck: true
    addComment: false
    addBadge: true
    addLabel: false